### ISSUE TITLE
Implement 2.01 "Segmentation and file size"

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#145] opened 2014-05-13 15:53 UTC
http://support.iatistandard.org/entries/61867937-File-size-and-segmentation

http://support.iatistandard.org/entries/57972186-Version-2-01-Iteration-1-8-Miscellaneous/

**Comment by caprenter** [comment] 2014-07-31 10:09
Assigning to Steven as he will be able to sort out where the guidance should go on the website, in any how to upgrade/migrate documents and perhaps elsewhere throughout the IATI architecture.

**Comment by stevieflow** [comment] 2015-01-21 14:51
duplicate of https://github.com/IATI/IATI-Extra-Documentation/issues/271

**Closed as completed by stevieflow** 2015-01-21 14:51 UTC
Labels: overview-pages
