### ISSUE TITLE
Administrative Area Codelists missing

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#65] opened 2014-04-07 14:50 UTC
I came across this issue when I was creating redirects for all codelists https://github.com/IATI/IATI-Standard-SSOT/issues/9

http://iatistandard.org/codelists/administrative_area_1/
http://iatistandard.org/codelists/administrative_area_2/

**Comment by stevieflow** [comment] 2014-04-07 15:19
I think they have always been missing/empty....

**Comment by Bjwebb** [comment] 2014-04-07 15:21
That was my impression. Currently though, there are pages to explain this. Currently these explanatory pages don't exist on the dev site.

**Comment by stevieflow** [comment] 2014-04-08 17:14
Duplicate of: https://github.com/IATI/IATI-Extra-Documentation/issues/17 ?

**Closed as completed by stevieflow** 2014-04-08 17:14 UTC
